import { Inter } from "next/font/google";
import "@/app/assets/fonts/lufga.css";
import "./globals.css";
import Header from "@/app/components/Header/Header";

const inter = Inter({ 
  subsets: ["latin"],
  weight: ['400', '500', '600', '700', '900' ],
  variable: '--font-inter',
});

export const metadata = {
  title: "Fleezo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
      <Header />
        {children}
      </body>
    </html>
  );
}
